# Generated by Django 6.0.7 on 2026-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_min',
            field=models.PositiveIntegerField(default=10, verbose_name='Stock mínimo'),
        ),
    ]
