# Generated by Django 6.0.7 on 2026-07-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nit', models.CharField(max_length=30, verbose_name='NIT')),
                ('categoria', models.CharField(choices=[('Papelería', 'Papelería'), ('Tecnología', 'Tecnología'), ('Mobiliario', 'Mobiliario'), ('Insumos', 'Insumos')], max_length=50, verbose_name='Categoría')),
                ('contacto', models.CharField(max_length=200, verbose_name='Contacto principal')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
