# Generated by Django 6.0.7 on 2026-09-08 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_proveedor_pedido_detallepedido_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('ultimo', models.PositiveBigIntegerField(default=0, verbose_name='Último número')),
            ],
            options={
                'verbose_name': 'Contador de documento',
                'verbose_name_plural': 'Contadores de documentos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Cliente')),
                ('cliente_documento', models.CharField(max_length=30, verbose_name='NIT/CC cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cliente')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA %')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('lineas', models.JSONField(default=list, verbose_name='Líneas (snapshot)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validada_dian', 'Validada DIAN'), ('error', 'Error de emisión'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('cufe', models.CharField(blank=True, default='', max_length=96, verbose_name='CUFE')),
                ('ubl_xml', models.TextField(blank=True, default='', verbose_name='UBL XML')),
                ('respuesta_dian', models.JSONField(blank=True, default=dict, verbose_name='Respuesta DIAN')),
                ('motivo_anulacion', models.TextField(blank=True, default='', verbose_name='Motivo anulación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='productos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_creadas', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='productos.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota crédito',
                'verbose_name_plural': 'Notas crédito',
                'ordering': ['-fecha'],
            },
        ),
    ]
